Repository spyder-ide/docrepr, pull requests merged in 2022-01, with the labels that each got.

#33 Add tests and CIs, upgrade packaging and metafiles, drop Py2 and add Py3.10, standardize infra and config, and more
  .gitattributes
  .github/FUNDING.yaml
  .github/workflows/test.yaml
  .gitignore
  AUTHORS.md
  LICENSE.txt
  MANIFEST.in
  conftest.py
  docrepr/__init__.py
  docrepr/_version.py
  docrepr/conf.py
  docrepr/js/math_config.js
  docrepr/js/utils.js
  docrepr/sphinxify.py
  docrepr/static/css/pygments.css
  docrepr/templates/layout.html
  docrepr/templates/rich_repr.html
  docrepr/tests/__init__.py
  docrepr/tests/test_output.py
  docrepr/utils.py
  fabfile.py
  pyproject.toml
  pytest.ini
  setup.cfg
  setup.py
Labels: type:Task

#35 Ignore spurious ResourceWarning in tests when opening the rendered result in the browser on Linux
  conftest.py
Labels: type:Bug

#36 Add ability to render Sphinx-format docstrings
  docrepr/sphinxify.py
  docrepr/tests/test_output.py
Labels: type:Enhancement

#40 Fix and improve definition extraction, avoid deprecated/removed calls and clean up other issues
  docrepr/sphinxify.py
  docrepr/tests/test_output.py
  docrepr/utils.py
Labels: type:Bug, type:Task

#41 Add visual regression tests with playwright
  .github/pull_request_template.md
  .github/workflows/test.yaml
  .github/workflows/update_reference_screenshots.yaml
  .github/workflows/visual_regression_test.yaml
  .gitignore
  conftest.py
  docrepr/tests/reference_screenshots/test-basic-darwin.png
  docrepr/tests/reference_screenshots/test-basic-linux.png
  docrepr/tests/reference_screenshots/test-basic-win32.png
  docrepr/tests/reference_screenshots/test-class_nosphinx_python_docs-darwin.png
  docrepr/tests/reference_screenshots/test-class_nosphinx_python_docs-linux.png
  docrepr/tests/reference_screenshots/test-class_nosphinx_python_docs-win32.png
  docrepr/tests/reference_screenshots/test-class_sphinx-darwin.png
  docrepr/tests/reference_screenshots/test-class_sphinx-linux.png
  docrepr/tests/reference_screenshots/test-class_sphinx-win32.png
  docrepr/tests/reference_screenshots/test-collapse-darwin.png
  docrepr/tests/reference_screenshots/test-collapse-linux.png
  docrepr/tests/reference_screenshots/test-collapse-win32.png
  docrepr/tests/reference_screenshots/test-empty_oinfo-darwin.png
  docrepr/tests/reference_screenshots/test-empty_oinfo-linux.png
  docrepr/tests/reference_screenshots/test-empty_oinfo-win32.png
  docrepr/tests/reference_screenshots/test-function_nosphinx_python_docs-darwin.png
  docrepr/tests/reference_screenshots/test-function_nosphinx_python_docs-linux.png
  docrepr/tests/reference_screenshots/test-function_nosphinx_python_docs-win32.png
  docrepr/tests/reference_screenshots/test-function_sphinx-darwin.png
  docrepr/tests/reference_screenshots/test-function_sphinx-linux.png
  docrepr/tests/reference_screenshots/test-function_sphinx-win32.png
  docrepr/tests/reference_screenshots/test-method_nosphinx_thirdparty-darwin.png
  docrepr/tests/reference_screenshots/test-method_nosphinx_thirdparty-linux.png
  docrepr/tests/reference_screenshots/test-method_nosphinx_thirdparty-win32.png
  docrepr/tests/reference_screenshots/test-method_sphinx-darwin.png
  docrepr/tests/reference_screenshots/test-method_sphinx-linux.png
  docrepr/tests/reference_screenshots/test-method_sphinx-win32.png
  docrepr/tests/reference_screenshots/test-no_docstring-darwin.png
  docrepr/tests/reference_screenshots/test-no_docstring-linux.png
  docrepr/tests/reference_screenshots/test-no_docstring-win32.png
  docrepr/tests/reference_screenshots/test-no_render_math-darwin.png
  docrepr/tests/reference_screenshots/test-no_render_math-linux.png
  docrepr/tests/reference_screenshots/test-no_render_math-win32.png
  docrepr/tests/reference_screenshots/test-numpy_module-darwin.png
  docrepr/tests/reference_screenshots/test-numpy_module-linux.png
  docrepr/tests/reference_screenshots/test-numpy_module-win32.png
  docrepr/tests/reference_screenshots/test-numpy_sin-darwin.png
  docrepr/tests/reference_screenshots/test-numpy_sin-linux.png
  docrepr/tests/reference_screenshots/test-numpy_sin-win32.png
  docrepr/tests/reference_screenshots/test-outline-darwin.png
  docrepr/tests/reference_screenshots/test-outline-linux.png
  docrepr/tests/reference_screenshots/test-outline-win32.png
  docrepr/tests/reference_screenshots/test-plot-darwin.png
  docrepr/tests/reference_screenshots/test-plot-linux.png
  docrepr/tests/reference_screenshots/test-plot-win32.png
  docrepr/tests/reference_screenshots/test-python_docs-darwin.png
  docrepr/tests/reference_screenshots/test-python_docs-linux.png
  docrepr/tests/reference_screenshots/test-python_docs-win32.png
  docrepr/tests/reference_screenshots/test-render_math-darwin.png
  docrepr/tests/reference_screenshots/test-render_math-linux.png
  docrepr/tests/reference_screenshots/test-render_math-win32.png
  docrepr/tests/test_output.py
  pytest.ini
  setup.cfg
Labels: type:Enhancement

#43 Add contributing guide/docs & security policy, and update/standardize readme, release guide, license info, & links
  AUTHORS.md
  CONTRIBUTING.md
  LICENSE.txt
  README.md
  RELEASE.md
  SECURITY.md
  conftest.py
  docrepr/__init__.py
  docrepr/conf.py
  docrepr/js/bootstrap.js
  docrepr/js/collapse_sections.js
  docrepr/js/copy_button.js
  docrepr/js/fix_image_paths.js
  docrepr/js/math_config.js
  docrepr/js/move_outline.js
  docrepr/js/utils.js
  docrepr/sphinxext/__init__.py
  docrepr/sphinxify.py
  docrepr/static/css/bootstrap.css
  docrepr/static/css/default.css
  docrepr/templates/layout.html
  docrepr/templates/rich_repr.html
  docrepr/templates/warning.html
  docrepr/tests/__init__.py
  docrepr/tests/test_output.py
  docrepr/utils.py
Labels: type:Task

#44 Release Docrepr 0.2.0
  CHANGELOG.md
  docrepr/__init__.py
Labels: type:Task
